---
version: 1.4.4
slug: test
name: Test
description: Test
url: https://github.com/home-assistant/hassio-addons/tree/master/dnsmasq
advanced: true
arch:
  - aarch64
image: homeassistant/aarch64-addon-dnsmasq
init: false
options:
  defaults:
    - 8.8.8.8
    - 8.8.4.4
  forwards: []
  hosts: []
  services: []
ports:
  53/tcp: 53
  53/udp: 53
schema:
  defaults:
    - str
  forwards:
    - domain: str
      server: str
  hosts:
    - host: str
      ip: str
  services:
    - host: str
      port: str
      priority: int
      srv: str
      weight: int
startup: system