name: Ecocomfort Broker add-on
version: 2.0.1
slug: ecocomfort-broker
description: Ecocomfort Broker
url: https://github.com/fabiocastagnino/home-assistant-addons/tree/main/ecocomfort-broker
arch:
  - aarch64
advanced: true
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
ports:
  1084/tcp: 1084
startup: system
image: fabiocastagnino/homeassistant-addon-intelliclima-broker
